- hosts: localhost
  connection: local
  become: true
 
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        autoremove: yes
        upgrade: yes
      changed_when: true
   
  tasks:
    - include: tasks/init.yml
    #- include: tasks/stats.yml
    - include: tasks/deepstream-pre.yml