- hosts: localhost
  connection: local
  become: true
 
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        autoremove: yes
        upgrade: yes
      changed_when: true
      
  vars_prompt:
    - name: remove_cmake
      prompt: "Do you want to continue?"
      private: yes

  tasks:
    - include: tasks/init.yml
    #- include: tasks/stats.yml
    #- include: tasks/deepstream-pre.yml
    #- include: tasks/deepstream.yml
    - include: tasks/cmake.yml
    #- include: tasks/tensort.yml
    #- include: tasks/ztier.yml