- name: cmake Install
  become: true
  expect:
    command: sudo apt remove --purge --auto-remove cmake
    chdir: /home/jetson
    responses:
      'Do you want to continue?' : 'y'
      'Do you want to continue?' : 'y'

  
- become: true
  command: sudo wget https://github.com/Kitware/CMake/releases/download/v3.13.5/cmake-3.13.5.tar.gz
  args:
    chdir: /home/jetson

- become: true
  command:  tar xvf cmake-3.13.5.tar.gz
  args:
    chdir: /home/jetson

- become: true
  command: sudo ./configure
  args:
    chdir: cmake-3.13.5

- become: true
  command: sudo make -j$(nproc)
  args:
    chdir: cmake-3.13.5

- become: true
  command: sudo make install
  args:
    chdir: cmake-3.13.5

- become: true
  command: sudo ln -s /usr/local/bin/cmake /usr/bin/cmake
  args:
    chdir: cmake-3.13.5