- name: Install packages
  become: true
  apt:
    name:
      - libssl1.0.0
      - libgstreamer1.0-0
      - gstreamer1.0-tools
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libgstrtspserver-1.0-0
      - libjansson4=2.11-1

- name: Git install librdkafka
  git:
    repo: 'https://github.com/edenhill/librdkafka.git'
    dest: /home/librdkafka

- command: git reset --hard 7101c2310341ab3f4675fc565f64f0967e135a6a
  args:
    chdir: /home/librdkafka

- name: configure
  become: true
  command: sudo ./configure
  args: 
    chdir: /home/librdkafka
  

- name: make
  become: yes
  make:
    chdir: /home/librdkafka
    target: install

- name: New Directory
  file:
    path: /opt/nvidia/deepstream/deepstream-5.1/lib
    state: directory

- command: sudo cp /usr/local/lib/librdkafka* /opt/nvidia/deepstream/deepstream-5.1/lib
    

 

  
