- name: Install packages
  become: true
  apt:
    name:
      - libssl1.0.0
      - libgstreamer1.0-0
      - gstreamer1.0-tools
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libgstrtspserver-1.0-0
      - libjansson4=2.11-1

- name: Git Install
  git:
    repo: 'https://github.com/edenhill/librdkafka.git'
    dest: /home/librdkafka

 
 

  
