- name: Install packages
  apt:
    name:
      - libssl1.0.0
      - libgstreamer1.0-0
      - gstreamer1.0-tools
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libgstrtspserver-1.0-0
      - libjansson4=2.11-1

- name: Install libdrkafka
  ansible.builtin.command: git clone https://github.com/edenhill/librdkafka.git
  chdir: /home/librdkafka
  ansible.builtin.command: git reset --hard 7101c2310341ab3f4675fc565f64f0967e135a6a
  ansible.builtin.command: ./configure
  ansible.builtin.command: make
  ansible.builtin.command: sudo make install
  ansible.builtin.command: sudo mkdir -p /opt/nvidia/deepstream/deepstream-5.1/lib
  ansible.builtin.command: sudo cp /usr/local/lib/librdkafka* /opt/nvidia/deepstream/deepstream-5.1/lib

  
